#version 460

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0, rgba16f) uniform image2D outImage;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outImage);

	if (coord.x < size.x && coord.y < size.y) {

		vec4 color = vec4(0.0, 0.0, 0.0, 1.0);
		if (gl_LocalInvocationID.x != 0 && gl_LocalInvocationID.y != 0) {
			color.r = float(coord.x) / float(size.x);
			color.g = float(coord.y) / float(size.y);
		}
		imageStore(outImage, coord, color);
	}
}
